Types: Improve type mapping for scalars and arrays
crate/sqlalchemy-cratedb pull request #24
Opened 2024-01-16 00:00 UTC by amotl

## About
AFAIK, this is needed for reverse type lookups / reflections.

## References
- This is coming from another [monkeypatch to meltano-target-cratedb](https://github.com/crate-workbench/meltano-target-cratedb/blob/2b20640/target_cratedb/sqlalchemy/patch.py#L22-L29).
- It is related to GH-23.

## Backlog
- [ ] Software tests.
- [ ] Just a short note about type support within the documentation.

2025-04-11 19:57 UTC, amotl commented
Dear @CaselIT,

may we humbly ask you to give this patch a quick review? We started to overhaul the type mapping of the CrateDB dialect the other day, and would like to conclude this patch.

Other than filling some gaps, we found that mapping database types to the uppercase type symbol variants provided by SQLAlchemy and back (i.e. using `sa.VARCHAR` rather than `sa.String`), offers better (reverse) type mapping behaviour with downstream frameworks like pandas or previous versions of Ibis and friends. Do you also think it is the right choice to do it this way?

With kind regards,
Andreas.

2025-04-11 22:04 UTC, amotl commented
Thank you!

2026-06-04 07:54 UTC, bgunebakan requested changes
Thank you, There are 2 small things. Could you check?

2026-06-04 07:54 UTC, bgunebakan commented on src/sqlalchemy_cratedb/dialect.py
>      TYPES_MAP["timestamp_array"] = ARRAY(sqltypes.TIMESTAMP(timezone=False))
`timestamp_array` written twice

```suggestion
    TYPES_MAP["timestamp_array"] = ARRAY(sqltypes.TIMESTAMP(timezone=False))
```

2026-06-04 07:54 UTC, bgunebakan commented on src/sqlalchemy_cratedb/dialect.py
> +    TYPES_MAP["real_array"] = ARRAY(DOUBLE)
Is it correct to map them to `DOUBLE`? CrateDB real is [32bit float](https://cratedb.com/docs/crate/reference/en/latest/general/ddl/data-types.html), but `DOUBLE` is 64bit.

2026-06-04 10:53 UTC, amotl commented on src/sqlalchemy_cratedb/dialect.py
>      TYPES_MAP["timestamp_array"] = ARRAY(sqltypes.TIMESTAMP(timezone=False))
Thank you. Fixed with 5280304b5f1.

2026-06-04 10:53 UTC, amotl commented on src/sqlalchemy_cratedb/dialect.py
> +    TYPES_MAP["real_array"] = ARRAY(DOUBLE)
Thank you. Also fixed with 5280304b5f1: `real` and `real_array` have already been assigned previously, so I removed those (wrong) redundancies.

2026-06-04 11:04 UTC, kneth approved these changes
LGTM

2026-06-04 15:35 UTC, bgunebakan approved these changes
Thanks!

2026-06-04 21:23 UTC, merged