Types: Emulate PostgreSQL's `JSON(B)` types using CrateDB's `OBJECT`
crate/sqlalchemy-cratedb pull request #27
Opened 2024-01-16 02:02 UTC by amotl

## About
The test suite of `meltano-tap-cratedb`, derived from the corresponding PostgreSQL adapter, is using PostgreSQL's `JSON` and `JSONB` types. By emulating them using CrateDB's `OBJECT` type, the corresponding test cases succeed without further ado. 💯

## References
This is coming from a [monkeypatch to meltano-tap-cratedb](https://github.com/crate-workbench/meltano-tap-cratedb/blob/b1b7a6d2/tap_cratedb/patch.py#L52-L65).

## Backlog
- [ ] Software tests.
- [ ] Changelog item.
- [ ] Update documentation section about type support.

2026-06-04 11:38 UTC, kneth commented on tests/compiler_test.py
> +            \tjson OBJECT
What if the column policy is `strict`? Do we need a test of that case?

2026-06-04 22:37 UTC, amotl commented on tests/compiler_test.py
> +            \tjson OBJECT
Good point.

`column_policy = 'strict'` is a table option. I don't think the dialect currently implements it, and I don't know if it has any impact on columns that are defined as OBJECT without qualifier.

The dialect currently provides the options crate_number_of_shards, crate_clustered_by, crate_number_of_replicas, crate_partitioned_by, crate_index, crate_columnstore, no column policy option in sight.

Other than this, the object type does not seem to implement any specials wrt. DDL generation.

https://github.com/crate/sqlalchemy-cratedb/blob/889c7670960d28124746ee20a7eacbb2e538af45/src/sqlalchemy_cratedb/type/object.py#L64-L79

2026-06-04 22:38 UTC, amotl commented on tests/compiler_test.py
> +            \tjson OBJECT
@coderabbitai: Please converge this conversation into a dedicated issue.

2026-06-08 12:06 UTC, kneth approved these changes
With the created issue for later, I say it LGTM

2026-06-08 13:24 UTC, amotl commented
Thanks for acknowledging. Please merge at your disposal, I've currently lost relevant capabilities.

2026-06-12 07:13 UTC, bgunebakan requested changes
Thank you, looks good, there is just small comments.

2026-06-12 07:13 UTC, bgunebakan commented on tests/compiler_test.py
> +    def test_ddl_with_json_columns(self):
Should we add a `JSONB` test case?

2026-06-12 07:13 UTC, bgunebakan commented on tests/compiler_test.py
> +        )  # noqa: W291, W293
I think this is typo and not needed here

2026-06-12 08:21 UTC, amotl commented
Hi @bgunebakan. Thank you for looking into this. Please take over and add missing bits at your disposal. Thank you!

2026-06-12 13:05 UTC, bgunebakan approved these changes

2026-06-12 13:06 UTC, merged